spring.application.name=springboot-cqrs
# mongodb
spring.data.mongodb.database=deposit_documents
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
logging.level.org.springframework.data.mongodb.core.MongoTemplate=debug
# redis
redis.pubsub.topic=deposit_events