spring.application.name=springboot-cqrs
# mongodb
spring.data.mongodb.database=deposit_store
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
logging.level.org.springframework.data.mongodb.core.MongoTemplate=debug
# redis
com.github.manerajona.redis.pubsub.topic-name=deposit_events
# currency
com.github.manerajona.deposits.default-currency=USD