### Create deposit
POST {{urlDeposits}}
Content-Type: application/json

{
  "accountNumber": 122333,
  "amount": 10.24
}

### Update deposit status
PATCH {{urlDeposits}}/f6cc63b0-2341-4692-ac12-0fba7582f1a7
Content-Type: application/json

{
  "status": "COMPLETED"
}

### Get all
GET {{urlDeposits}}

### Get by guid
GET {{urlDeposits}}/f6cc63b0-2341-4692-ac12-0fba7582f1a7